version: "3"
services:
  ngroktunnel:
    build:
      context: .
    environment:
      NGROK_REGION: eu
      TARGET_HOST: nginx
      TARGET_PORT: 80
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    depends_on:
      - testservice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  testservice:
    image: nginx:latest
    ports:
      - 80:80
