version: "3"
services:
  ngroktunnel:
    build:
      context: .
    environment:
      NGROK_REGION: eu
      TARGET_HOST: nginx
      TARGET_PORT: 80
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    depends_on:
      - my-service
    environment:
      # Define the nginx target here
      - TARGET_HOST_AND_PORT=my-service:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # Add your target service here
  my-service:
    image: nginx:latest
    ports:
      - 80:80
